server:
  host: 0.0.0.0
  port: 8080
  mode_run: debug
  level_log: 5

database:
  host: localhost
  port: 3306
  database_name: food_delivery
  username: root
  password: root

sms:
  account_sid: AC131be1434e5d1203c5cf2aec0ecc072c
  auth_token: 34a036e3f4432f4802c416895bd489d9
  my_phone_number: +14752671195